# Generated by Django 3.1.3 on 2021-03-13 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentDetail',
            fields=[
                ('enroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.student')),
                ('name', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('add', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='add',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
