# Generated by Django 3.1.3 on 2021-03-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210313_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='hello', max_length=32),
            preserve_default=False,
        ),
    ]
